In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
a+2

array([3, 4, 5, 6])

In [5]:
a-2

array([-1,  0,  1,  2])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [9]:
a**2

array([ 1,  4,  9, 16])

In [10]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [11]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [12]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# linear Algebra

In [13]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [14]:
# find the determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [15]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [16]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a=np.min(stats)
b=np.min(stats, axis=0)  # min of each column 
c=np.min(stats, axis=1)  # min of each row
print(a)
print(b)
print(c)

1
[1 2 3]
[1 4]


In [19]:
np.sum(stats)

np.int64(21)

In [20]:
np.sum(stats, axis=1)

array([ 6, 15])