In [24]:
import numpy as np

In [25]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [27]:
# Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [28]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [29]:
# Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [36]:
print(a.itemsize)
print(b.itemsize)

4
8


In [37]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

12
12
